server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/graydelay/spring-cloud-config.git
#          uri: file:///Users/journey/study/spring-cloud/git-local-repo