server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/journey/study/spring-cloud/native-file-repo
        git:
          uri: https://github.com/graydelay/spring-cloud-config.git
#          uri: file:///Users/journey/study/spring-cloud/git-local-repo